import { Platform, StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FFFFFF",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingTop: Platform.OS === "ios" ? 10 : 20,
    paddingBottom: 15,
    backgroundColor: "#FFFFFF",
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: "800",
    color: "#1F2937",
    textAlign: "center",
  },
  scrollContent: {
    padding: 24,
    paddingBottom: 60,
  },
  label: {
    fontSize: 15,
    fontWeight: "700",
    color: "#374151",
    marginBottom: 8,
    marginTop: 20,
  },
  input: {
    borderWidth: 1,
    borderColor: "#F3F4F6",
    borderRadius: 14,
    padding: 14,
    fontSize: 15,
    backgroundColor: "#F9FAFB",
    color: "#1F2937",
  },
  dropdown: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#F3F4F6",
    borderRadius: 14,
    padding: 14,
    backgroundColor: "#F9FAFB",
  },
  placeholder: {
    color: "#9CA3AF",
    fontSize: 14,
  },
  row: {
    flexDirection: "row",
    gap: 12,
  },
  textArea: {
    height: 120,
    paddingTop: 14,
  },
  uploadBox: {
    borderWidth: 1.5,
    borderColor: "#E0E4FF",
    borderStyle: "dashed",
    borderRadius: 16,
    height: 140,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#F8F9FF",
    marginTop: 4,
  },
  uploadText: {
    marginTop: 10,
    color: "#7A82FF",
    fontSize: 14,
    fontWeight: "600",
  },
  fileNameText: {
    marginTop: 8,
    color: "#10B981",
    fontSize: 13,
    fontWeight: "500",
  },
  checkboxRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginTop: 28,
  },
  checkbox: {
    width: 22,
    height: 22,
    borderWidth: 1.5,
    borderColor: "#7A82FF",
    borderRadius: 6,
    marginRight: 10,
    justifyContent: "center",
    alignItems: "center",
  },
  checkboxInner: {
    width: 12,
    height: 12,
    backgroundColor: "#7A82FF",
    borderRadius: 2,
  },
  checkboxActive: {
    backgroundColor: "#7A82FF",
  },
  checkboxText: {
    fontSize: 13,
    color: "#4B5563",
    flex: 1,
    lineHeight: 20,
  },
  submitButton: {
    backgroundColor: "#7A82FF",
    borderRadius: 30,
    height: 54,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 35,
    // Shadow for iOS
    shadowColor: "#7A82FF",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.25,
    shadowRadius: 10,
    // Shadow for Android
    elevation: 8,
  },
  submitButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "700",
    letterSpacing: 0.5,
  },
});
