import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F8F9FC",
  },
  header: {
    paddingHorizontal: 20,
    paddingTop: 10,
    paddingBottom: 20,
  },
  headerTitle: {
    fontSize: 26,
    fontWeight: "bold",
    color: "#111",
    marginBottom: 16,
  },
  headerActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  iconButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#fff",
  },
  pillButton: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#111",
    backgroundColor: "#fff",
    gap: 6,
  },
  pillButtonText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#111",
  },
  pillButtonPrimary: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#7A82FF",
    backgroundColor: "#fff",
    gap: 4,
  },
  pillButtonTextPrimary: {
    fontSize: 14,
    fontWeight: "600",
    color: "#7A82FF",
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingBottom: 40,
  },
  summaryContainer: {
    gap: 16,
    marginBottom: 24,
  },
  row: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    width: "100%",
  },
  card: {
    flex: 1,
    borderRadius: 16,
    padding: 20,
    justifyContent: "center",
  },
  cardPurple: {
    backgroundColor: "#E2E5FF",
  },
  cardWhite: {
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E2E5FF",
  },
  cardDark: {
    backgroundColor: "#353744",
  },
  iconBox: {
    width: 46,
    height: 46,
    borderRadius: 23,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 16,
  },
  iconBoxWhite: {
    backgroundColor: "#fff",
  },
  iconBoxOutline: {
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#7A82FF",
  },
  cardTitleText: {
    fontSize: 12,
    color: "#555",
    marginTop: 8,
  },
  cardValuePurple: {
    fontSize: 16, // ลดขนาดลงจากเดิมนิดหน่อยถ้ามี 3 columns
    fontWeight: "bold",
    color: "#7A82FF",
    marginTop: 4,
  },
  totalBalanceHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 16,
  },
  withdrawButton: {
    backgroundColor: "#fff",
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
  },
  withdrawButtonText: {
    color: "#7A82FF",
    fontWeight: "bold",
    fontSize: 14,
  },
  cardTitleWhite: {
    fontSize: 14,
    fontWeight: "600",
    color: "#A0A3B5",
    marginBottom: 4,
  },
  cardValueWhite: {
    fontSize: 32,
    fontWeight: "bold",
    color: "#fff",
  },
  recentSection: {
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 20,
    borderWidth: 1,
    borderColor: "#F0F0F0",
  },
  recentTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#111",
    marginBottom: 16,
  },
  listItem: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 20,
  },
  listIconBox: {
    width: 44,
    height: 44,
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
  listIconBoxPurple: {
    backgroundColor: "#F0F2FF",
    borderWidth: 1,
    borderColor: "#E2E5FF",
  },
  listIconBoxYellow: {
    backgroundColor: "#FFF9E6",
    borderWidth: 1,
    borderColor: "#FDE68A",
  },
  listTextContainer: {
    flex: 1,
    justifyContent: "center",
  },
  listTitle: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#333",
    marginBottom: 2,
  },
  listSubtitle: {
    fontSize: 12,
    color: "#888",
  },
  listAmount: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#4CAF50",
    marginLeft: 10,
  },
  // --- Chart Section ---
  chartSection: {
    gap: 12,
    marginTop: 8,
  },
  chartCard: {
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 16,
    shadowColor: "#000",
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
  },
  topSheetBanner: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFFBEB",
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: "#FDE68A",
  },
  topSheetLabel: {
    fontSize: 11,
    color: "#92400E",
  },
  topSheetTitle: {
    fontSize: 13,
    fontWeight: "600",
    color: "#78350F",
  },
  topSheetRevenue: {
    fontSize: 15,
    fontWeight: "700",
    color: "#F59E0B",
  },

  // --- Review Detail Modal ---
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.45)",
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  modalContainer: {
    backgroundColor: "#fff",
    borderRadius: 24,
    maxHeight: "80%",
    width: "100%",
    paddingBottom: 32,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#F0F0F0",
  },
  modalHeaderTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#111",
  },
  modalCloseButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#F3F4F6",
    justifyContent: "center",
    alignItems: "center",
  },
  modalBody: {
    paddingHorizontal: 20,
    paddingTop: 16,
  },
  modalSheetInfo: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F8F9FF",
    borderRadius: 14,
    padding: 14,
    borderWidth: 1,
    borderColor: "#E2E5FF",
  },
  modalSheetIconBox: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: "#E2E5FF",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
  modalSheetLabel: {
    fontSize: 11,
    color: "#888",
    marginBottom: 2,
  },
  modalSheetTitle: {
    fontSize: 14,
    fontWeight: "600",
    color: "#333",
  },
  modalDivider: {
    height: 1,
    backgroundColor: "#F0F0F0",
    marginVertical: 16,
  },
  modalReviewerRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
  },
  modalAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    marginRight: 12,
  },
  modalAvatarPlaceholder: {
    backgroundColor: "#F3F4F6",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  modalReviewerName: {
    fontSize: 15,
    fontWeight: "600",
    color: "#333",
  },
  modalReviewDate: {
    fontSize: 12,
    color: "#999",
    marginTop: 2,
  },
  modalRatingRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
    backgroundColor: "#FFFBEB",
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: "#FDE68A",
  },
  modalRatingText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#92400E",
    marginLeft: 8,
  },
  modalCommentBox: {
    backgroundColor: "#F8F9FC",
    borderRadius: 14,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  modalCommentLabel: {
    fontSize: 12,
    fontWeight: "600",
    color: "#888",
    marginBottom: 8,
  },
  modalCommentText: {
    fontSize: 15,
    lineHeight: 22,
    color: "#333",
  },

  // --- Reviews List Modal Items ---
  reviewListItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: "#F0F0F0",
  },
  reviewListItemLeft: {
    flex: 1,
    flexDirection: "row",
    alignItems: "flex-start",
  },
  reviewListComment: {
    fontSize: 12,
    color: "#999",
    fontStyle: "italic",
    marginTop: 3,
  },
});
